### ISSUE TITLE
Can't open "secured" PDFs

### ISSUE THREAD

**Issue by efrainsteinbach** [empira/PDFsharp-1.5#46]
I have an issue with PDF documents that have an owner password and/or some odd content compression, like this one:

https://www.swissfunddata.ch/sfdpub/docs/kid-8059_08_05-20180208-en.pdf 

PDFsharp fails to open them (and also crashes when looking up the exception message). I'm not entirely sure what goes wrong and whether it would all be fine if the owner password was available.

Btw, my use case is that I need to combine multiple documents like this one into one big document which can be printed more easily (i.e. the user doesn't have to open and print them one by one).

**Comment by ThomasHoevel** [comment]
The exception I get is this: "The PDF document is protected with an encryption not supported by PDFsharp."

So it's not a bug, it's a feature.

I'm afraid the new encryption is not on the roadmap and will not be implemented in the foreseeable future.

**Comment by efrainsteinbach** [comment]
Hehe, of course, it's just something that doesn't work yet and it would be great if it did. 
Also... well, iTextSharp supports it! 😉

Can you confirm that this kind of encryption is some open standard? Maybe I can do some digging..

In any case, I'm 100% positive that something is not right with the resources file for the exception - at least on my machine (i.e. I get the same error with the nuget assemblies and when I build the git repo myself):

```
StackTrace:	
at System.Resources.ManifestBasedResourceGroveler.HandleResourceStreamMissing(String fileName)
   at System.Resources.ManifestBasedResourceGroveler.GrovelForResourceSet(CultureInfo culture, Dictionary`2 localResourceSets, Boolean tryParents, Boolean createIfNotExists, StackCrawlMark& stackMark)
   at System.Resources.ResourceManager.InternalGetResourceSet(CultureInfo requestedCulture, Boolean createIfNotExists, Boolean tryParents, StackCrawlMark& stackMark)
   at System.Resources.ResourceManager.InternalGetResourceSet(CultureInfo culture, Boolean createIfNotExists, Boolean tryParents)
   at System.Resources.ResourceManager.GetString(String name, CultureInfo culture)
   at System.Resources.ResourceManager.GetString(String name)
   at PdfSharp.PSSR.TestResourceMessages() in C:\Work\PDFsharp.git\src\PdfSharp\root\PSSR.cs:line 385
   at PdfSharp.PSSR..cctor() in C:\Work\PDFsharp.git\src\PdfSharp\root\PSSR.cs:line 395
--- End of inner exception stack trace ---
    at PdfSharp.PSSR.get_UnknownEncryption()
   at PdfSharp.Pdf.Security.PdfStandardSecurityHandler.ValidatePassword(String inputPassword) in C:\Work\PDFsharp.git\src\PdfSharp\Pdf.Security\PdfStandardSecurityHandler.cs:line 240
   at PdfSharp.Pdf.IO.PdfReader.Open(Stream stream, String password, PdfDocumentOpenMode openmode, PdfPasswordProvider passwordProvider) in C:\Work\PDFsharp.git\src\PdfSharp\Pdf.IO\PdfReader.cs:line 503
   at PdfSharp.Pdf.IO.PdfReader.Open(Stream stream, String password, PdfDocumentOpenMode openmode) in C:\Work\PDFsharp.git\src\PdfSharp\Pdf.IO\PdfReader.cs:line 272
   at PdfSharp.Pdf.IO.PdfReader.Open(Stream stream, PdfDocumentOpenMode openmode) in C:\Work\PDFsharp.git\src\PdfSharp\Pdf.IO\PdfReader.cs:line 257
   at UnitTestProject1.UnitTest1.TestMethod1() in C:\Work\PDFsharp.git\src\UnitTestProject1\UnitTest1.cs:line 17
Result Message:	
Test method UnitTestProject1.UnitTest1.TestMethod1 threw exception: 
System.TypeInitializationException: The type initializer for 'PdfSharp.PSSR' threw an exception. ---> System.Resources.MissingManifestResourceException: Could not find any resources appropriate for the specified culture or the neutral culture.  Make sure "PdfSharp.Resources.Messages.resources" was correctly embedded or linked into assembly "PdfSharp-gdi" at compile time, or that all the satellite assemblies required are loadable and fully signed.
Result StandardOutput:	Debug Trace:
The type initializer for 'PdfSharp.PSSR' threw an exception.


```

**Comment by ThomasHoevel** [comment]
AFAIK PDF is an ISO standard. I don't know if some encryptions are excluded from the ISO standard.

**Comment by efrainsteinbach** [comment]
Sure, I've seen the ISO-32000-1 standard specification - a horrific piece! 😅
I was just looking for some pointers...

**Comment by ThomasHoevel** [comment]
PDF encryption is not my area of expertise. I don't know when this encryption type was introduced - maybe you can find it in the PDF 1.5 reference already, but I'm not sure.  
Finding relevant information in the PDF reference can be a challenge.

**Comment by ThomasHoevel** [comment]
The exception is thrown in the PdfStandardSecurityHandler class in this method:

```csharp
public PasswordValidity ValidatePassword(string inputPassword)
{
    // We can handle 40 and 128 bit standard encryption.
    string filter = Elements.GetName(PdfSecurityHandler.Keys.Filter);
    int v = Elements.GetInteger(PdfSecurityHandler.Keys.V);
    if (filter != "/Standard" || !(v >= 1 && v <= 3))
        throw new PdfReaderException(PSSR.UnknownEncryption);

```
So maybe the values of "filter" and "v" can get you started.

**Comment by efrainsteinbach** [comment]
OK, thanks!
